spring.application.name=prova1

spring.docker.compose.enabled=true

spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=validate

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.servlet.encoding.enabled=true

spring.thymeleaf.encoding=UTF-8

spring.datasource.url=jdbc:mysql://localhost:3306/db_filmes?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=usuario
spring.datasource.password=usuario123