services:

  mysql:

    image: 'mysql:8.1'
    container_name: db_filmes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - vol_dados_filmes:/var/lib/mysql

    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'

volumes:
  vol_dados_filmes:
    name: "vol_dados_filmes"