#spring.datasource.url=${MYSQL_DATABASE_URL}
#spring.datasource.username=${MYSQL_USER}
#spring.datasource.password=${MYSQL_PASSWORD}
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# Those lines aren't needed once running with docker composer

# Name
spring.application.name=Prova3_VSL

# Whether Docker Compose support is enabled
spring.docker.compose.enabled=true
# Enable or disable flyway
spring.flyway.enabled=true

# The line
# spring.jpa.hibernate.ddl-auto=update/validade
# was removed because hibernate was deleting everything that Flyway created
# and replacing it with blank tables based on the models

# Check for errors
spring.flyway.fail-on-missing-locations=true

# Change port to avoid conflict
server.port=8010

# Verbose JPA (everything was fixed, not needed any longer)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Case-sensitive (essential)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Thymeleaf cache (disable in dev)
spring.thymeleaf.cache=false

# Docker container will not be closed when application shutdown
#spring.docker.compose.lifecycle-management=start_only